version: "3.7"
services:
  # FRONTEND
  hr:
    build:
      context: ./frontend
      dockerfile: ./apps/hr/Dockerfile
    restart: always
    networks:
      - default

  employee:
    build:
      context: ./frontend
      dockerfile: ./apps/employee/Dockerfile
    restart: always
    networks:
      - default

  app:
    build:
      context: .
      target: backend
    env_file:
      - ./.env.deploy
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default

  db:
    image: registry.hub.docker.com/library/mysql:5.7
    volumes:
      - mysqlfolder:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 40s
      retries: 20
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - default

  docs:
    image: registry.hub.docker.com/swaggerapi/swagger-ui:v4.17.0
    restart: always
    environment:
      SWAGGER_JSON_URL: /docs/openapi.yaml
      BASE_URL: /docs
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: increase-productivity.abdrashitov-academy.ru
      VIRTUAL_PATH: /docs
      LETSENCRYPT_HOST: increase-productivity.abdrashitov-academy.ru
    volumes:
      - ./backend/openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro
    networks:
      - default
      - academy

  nginx:
    build:
      context: .
      target: nginx
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: increase-productivity.abdrashitov-academy.ru
      VIRTUAL_PATH: /
      LETSENCRYPT_HOST: increase-productivity.abdrashitov-academy.ru
    restart: always
    depends_on:
      - app
    networks:
      - default
      - academy

volumes:
  mysqlfolder:

networks:
  academy:
    name: academy
  default:
